import util
import os

# Create a list of all the paths to the raw x and y data generated from the
# original LabVIEW code.
print '\rBuilding a list of directories with raw data in them.'
PATH_STRING_1 = '/Volumes/science/projects/kinesin_and_microtubules'
PATH_STRING_2 = 'water_isotope_study/data'
BASE_PATH = os.path.join(PATH_STRING_1, PATH_STRING_2)
ASSAY_TYPE = 'heavy_hydrogen_buffer'
PATH = os.path.join(BASE_PATH, ASSAY_TYPE)
raw_data_paths = util.list_data_paths(PATH, 'Full')
LENGTH_RAW = len(raw_data_paths)

# Create a new directory that will contain data for the python scripts.
print '\rCreating python_data directories.'
for i,raw_data_file in enumerate(raw_data_paths):
    util.create_python_data_directory(raw_data_file)
    percent = float(i + 1)/LENGTH_RAW*100
    util.progress_bar(percent)

# Create a copy of the raw data generated by LabVIEW into the python_data
# directory.
print '\rCopying raw data files.'
for i,raw_data_file in enumerate(raw_data_paths):
    util.copy_raw_data(raw_data_file)
    percent = float(i + 1)/LENGTH_RAW*100
    util.progress_bar(percent)

# Smooth the raw x and y position data.
print '\rSmoothing data and saving it to the python_data directory.'
for i,raw_data_file in enumerate(raw_data_paths):
    util.smooth_raw_data(raw_data_file)
    percent = float(i + 1)/LENGTH_RAW*100
    util.progress_bar(percent)

# Calculate the speed data from the smoothed data.
smoothed_data_paths = util.list_data_paths(PATH, 'smoothed_data')
LENGTH_SMOOTHED = len(smoothed_data_paths)